name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Generate Renovate configuration
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: renovate-config.js.jinja
          output_file: renovate-config.js
          strict: true
          data_file: ${{ secrets.CONFIG_VALUES_FILE }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.164.0
        env:
          LOG_LEVEL: "debug"
        with:
          configurationFile: renovate-config.js
          token: "x-access-token:${{ steps.get_token.outputs.app_token }}"
